### ISSUE TITLE
ufw issue with cronjob

### ISSUE THREAD

**Issue by jseutens** [dajul/ufw-spamhaus#2]
doesn't work as cronjob , needed to replace all ufw commands with $UFW to get it working again with the latest update of UFW

**Comment by dajul** [comment]
It's better to setup paths inside "crontab -e", just like in the file /etc/crontab:
```

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
```
This way you can just use "ufw" inside the script
